### ISSUE TITLE
Doesn't give warning in return case

### ISSUE THREAD

**Issue by rythos42** [ykoksen/unused-task-warning#17] opened 2019-05-27 21:04 UTC
**NOTE**: See the added example below for more details.

I had expected the following example to give a warning, but it doesn't:

`using System.Threading.Tasks;

namespace ACF.UI.LoanOrigination.Gateway
{

	public interface ICallee
	{
		bool ProblemSolved { get; }
		Task<int> SolveProblemAsync();
	}

	public class Callee : ICallee
	{
		public bool ProblemSolved { get; set; }

		public async Task<int> SolveProblemAsync()
		{
			await Task.Delay(10);
			ProblemSolved = true;
			return 1;
		}
	}

	public class Caller
	{
		public bool DoCall()
		{
			ICallee xxx = new Callee();

			// This analyser will give a warning at the following line
			var i = xxx.SolveProblemAsync(); // This is most likely an undesired fire and forget. 

			return xxx.ProblemSolved; // Will return false - we expected it to return true
		}
	}
}
`
It's not a "fire and forget", but I'd like to know that I missed the await here.

**Comment by ykoksen** [comment] 2019-05-28 17:39
Now I have the chance: "This is by design".

Checking this would be really cumbersome - because I'd have to check if the variable `i` is ever used (`i` might perfectly well be awaited several lines later or perhaps even returned).  Normally I use some other analyser tool (ex. Resharper) that tells me that I have an unused variable.

When the `Task` is assigned to a variable the analyser expects that the user has decided to do an action with the variable - else there would be no idea in assigning it.

**Comment by ykoksen** [comment] 2019-05-28 17:45
But if you want there is already an optional rule for exactly this purpose that you can enable if you want to. See pull request #13. It currently doesn't work too well since there were/are some issues related to Visual Studio 2019, but I believe it is use-able.

**Comment by rythos42** [comment] 2019-05-28 17:46
Damn. My issue was that I was adding async to some DI'd middle-tier classes and assumed that the compiler would tell me I wasn't awaiting them (probably because Resharped used to...). So I ended up with some Web API controller methods blissfully returning Ok(result), when result changed from being a Result to being a Task<Result>. 

Here's a better example:

```
public interface ICallee
{
	Task<int> SolveProblemAsync();
}

public class Callee : ICallee
{
	public async Task<int> SolveProblemAsync()
	{
		await Task.Delay(10);
		return 1;
	}
}

public class Caller
{
	public IHttpActionResult DoCall() // should be Task<IHttpActionResult>
	{
		ICallee xxx = new Callee();
		var i = xxx.SolveProblemAsync(); // should probably be awaited in my situation.
		return Ok(i);
	}
}
```

Unfortunately we decided to stop using Resharper because of the cost of outfitting the development team with it, so I'm looking for another tool that could help with this.

**Comment by samusaran** [comment] 2019-05-28 17:50
The main issue here is that this analyzer, while useful, is affected by the same issues Resharper is.
While developing this kind of warnings, you can follow 2 roads:

- Handle only the most dangerous or important cases, which in return makes the Analyzer incomplete, since it doesn't detect special cases like the one shown
- Handle every specific cases, each and everyone configured\configurable separately, with the chance to being annoying, like Resharper sometimes does. The user will be forced to turn off some of them, but still, the analyzer would do it's job. It's the user that will have to tailor the precision with a Ruleset.

**Comment by ykoksen** [comment] 2019-05-28 18:02
@rythos42 Wow, you actually hit a rather rare situation where the change of type of `i` does not result in the code being broken. I don't believe Resharper would give a warning either. You are clearly using the variable.

I would like to extend the analyser to handle this, but I believe it would be really cumbersome and require more than double the time that has currently been spent on it - so I don't see it as feasible. It would require the analyser to check if the task was ever awaited.

**Comment by samusaran** [comment] 2019-05-28 18:12
I have a vague idea on how to make it work. If you want, I should have time in the next days.

**Comment by rythos42** [comment] 2019-05-28 18:15
Unfortunately this rare situation is going to be my bread-and-butter for the next while, as we're moving from a monolith to a microservice architecture and a lot of legacy things are going to start needing awaits!

It's all good if it's to much to handle - it's a free/hobby-project tool after all. :) If you have an idea and time, I'm interested!

**Comment by rythos42** [comment] 2019-05-28 18:44
I downloaded and compiled the trunk code and it's giving me a green squiggly that says "The method 'blah' returns a Task that was not awaited." This seems like what I'm looking for, although the fact that you guys are still thinking about tells me that maybe it isn't?

**Comment by samusaran** [comment] 2019-05-28 18:47
There are 2 types of warning. One that is default on, and one that is default off that handle your case, except that it doesn't detect if you used the Task after.

Example:
```
   var t = YouShouldAwaitThis(); // Warning, you should await this...
   Task.WaitAll(t); // ...even if the Task is actually (a)waited here
```

If you are debugging the analyzer, all warnings are on.

**Comment by rythos42** [comment] 2019-05-28 19:14
For me, right now, I'm ok if it doesn't defect if I await it after. That's not a scenario I'm looking at.

**Comment by ykoksen** [comment] 2019-05-30 17:49
@rythos42 note that in order to use this feature from NuGet you need to download the beta version (which I'd really appreciate, since the beta haven't been downloaded that much, and I'd like some feedback so we can get it released).

**Comment by samusaran** [comment] 2019-05-31 13:47
@ykoksen I've pushed https://github.com/samusaran/unused-task-warning/commit/e04427763284d3f804f94548f6d4da3a86878193 that should fix some of the issues, and also it enables the second check by default, since it is now less intrusive.

Basically the new version checks if the Task is actually used, so it works in the following cases:
```
var t = AsyncMethod(); // no warning, since t is awaited after;
// a lot of code
return await t;
```

```
static Task ReturnsATask()
{
   var t = Task.FromResult(0); // no warnings since t is returned directly. The warning may be issued on the caller
   return t;
}
```

```
var t = AsyncMethod(); // warning! this behaviour is probably unwanted
Console.WriteLine(t);
```

Right now, the only case that I still have to handle is the following:
```
var t = Task.FromResult(1); // Warning, t is not awaited
var r = t;
await r; // but since r and t are the same thing, t should have no warning
```

Please let me know what you think. I can open a new issue if you want.

**Comment by ykoksen** [comment] 2019-06-06 19:42
@samusaran looks good. I'll just reopen this issue.

I did come across a bug however. I tried the code in VS 2019 and got an exception:

> System.InvalidOperationException : Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at async Lindhart.Analyser.MissingAwaitWarning.LindhartAnalyserMissingAwaitWarningCodeFixProvider.RegisterCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)

The code was:
```
using System;
using System.IO;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program : ITest
    {
        static ITest test = new Program();

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            Task test2 = test.TestThis();

            Task.WaitAll(test2);
        }

        public async Task TestThis()
        {
            await File.AppendAllLinesAsync("test.txt", new []{ "Test"});
        }
    }

    public interface ITest
    {
        Task TestThis();
    }
}
```

The exception occurs when I try to click the light bulb for automatic fixing the problem.
![image](https://user-images.githubusercontent.com/29013502/59061477-ea180400-88a3-11e9-985f-7e8f563bdf8e.png)

**Comment by ykoksen** [comment] 2020-10-26 18:53
Since samusaran is no longer active this issue will be closed without being solved.

**Closed as completed by ykoksen** 2020-10-26 18:53 UTC
Labels: enhancement

**Comment by ClassyCircuit** [comment] 2023-07-21 15:40
@ykoksen  So it's not possible to get a warning when we return a method call without awaiting it?
I have the same issue as others - many missing await statements in controllers that are returning async method call results to views and then they silently fail during runtime.

**Comment by samusaran** [comment] 2023-07-21 15:44
Hi @janissimsons , the "strict mode" was made to handle that specific case, and that was the specific reason I collaborated to this project, because we had a massive Web API and we were transitioning to all sync, to all async.

If there is an error I may be able to fix it, but the last time I opened this project was more than 4 years ago.

**Comment by ykoksen** [comment] 2023-07-22 11:23
Hi @janissimsons 

> So it's not possible to get a warning when we return a method call without awaiting it?

Well - not currently in the case where you do put the return value in a variable. Currently this analyser only handles the case where the return value is not stored at all.
